### ISSUE TITLE
Release 2.13-1.0.1625170289.4e4665d is broken

### ISSUE THREAD

**Issue by andreisilviudragnea** [SimonJPegg/mvn_scalafmt#158]
**Describe the bug**
Release 2.13-1.0.1625170289.4e4665d does not detect source files anymore:
```
[WARNING] Could not locate Scala source at .../src/main/scala
[WARNING] Could not locate Scala source at .../src/test/scala
```

**Expected behavior**
Sources should be detected.

**Environment:**
    - OS: 

```
Darwin MacBook-Pro-5.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

    - maven version: 

```
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: /Users/dragnea/.sdkman/candidates/java/11.0.12-zulu/zulu-11.jdk/Contents/Home
Default locale: en_RO, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```

    - scalafmt version: 2.13-1.0.1625170289.4e4665d

Probably https://github.com/SimonJPegg/mvn_scalafmt/pull/149 introduced a regression.

**Comment by SimonJPegg** [comment]
Release [1.0.1630847570.668ef24 ](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/2.13-1.0.1630847570.668ef24) has reverted the change in #149. @kitbellew Do you want to have a look to see what the issue was?

**Comment by kitbellew** [comment]
@andreisilviudragnea can you share your pom file? how are the source and test source directories defined? do you have additional sources via a helper plugin?

also, is the error message literal, or `...` contains something else?

**Comment by jozic** [comment]
we had same issue, to overcome we had to explicitly set 
```xml
                        <sourceDirectories>
                            <sourceDirectory>src/main/scala</sourceDirectory>
                        </sourceDirectories>
                        <testSourceDirectories>
                            <testSourceDirectory>src/test/scala</testSourceDirectory>
                        </testSourceDirectories>
```
in plugin's `<configurtion>`

our pom always had 
```xml
        <sourceDirectory>src/main/scala</sourceDirectory>
        <testSourceDirectory>src/test/scala</testSourceDirectory>
```
in `<build>` and before `2.13-1.0.1625170289.4e4665d` it used to work

**Comment by kitbellew** [comment]
need to dedicate a little time soon...
