### ISSUE TITLE
consider supporting remote scalafmt.config location 

### ISSUE THREAD

**Issue by jozic** [SimonJPegg/mvn_scalafmt#20]
Very often same set of formatting rules are shared between projects. Would be really nice to let plugin know the git url and let it download `.scalafmt.conf`

**Comment by SimonJPegg** [comment]
TBH I'm probably not going to implement this.  It's a great idea, but I just don't have the free time at the minute.  If you'd like to open a merge request with the feature, I'd be happy to add it though.

**Comment by jozic** [comment]
Leaving this comment here for anyone who may think they also want this
https://daodecode.com/2018/11/23/share-scalafmt-configuration-with-git-submodules/

**Comment by SimonJPegg** [comment]
This has been added to the [1.0.0-RC2](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/v1.0.0-RC2) release candidate.

**Comment by jozic** [comment]
thank you!
