### ISSUE TITLE
Add an option to prohibit using default configuration if custom configuration is provided, but can't be loaded

### ISSUE THREAD

**Issue by jozic** [SimonJPegg/mvn_scalafmt#31]
So the issue is, if something happens with custom configuration file, the plugin just issues a warning and uses default configuration, which can mess up all the formatting.
I would like to have an option to fail the build if specified configuration file is missing

**Comment by SimonJPegg** [comment]
Added in https://github.com/SimonJPegg/mvn_scalafmt/pull/33 and released in [v0.11_1.5.1](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/v0.11_1.5.1)

**Comment by jozic** [comment]
looks like this is lost in 1.0.0
it was there in 0.12, but now this option is not recognized
did i miss something?

**Comment by SimonJPegg** [comment]
There's no default `configLocation` set, so if you don't specify one or provide an invalid path then the plugin will throw an exception.  It should be default behaviour now rather than an option.

**Comment by jozic** [comment]
oh, nice, makes sense
thank you
