### ISSUE TITLE
 2.12-1.1.1684076452.9f83818 not in maven central?

### ISSUE THREAD

**Issue by josephlbarnett** [SimonJPegg/mvn_scalafmt#339]
(this template is a suggestion, not a requirement)

**Describe the bug**
version 2.12-1.1.1684076452.9f83818 of the plugin does not appear in maven central, just the scala 2.13 version.  would be great to silence the parallel execution warnings.

**To Reproduce**
try to depend on plugin version 2.12-1.1.1684076452.9f83818 based on the existence of a release tag, get `Plugin org.antipathy:mvn-scalafmt_2.12:1.1.1684076452.9f83818 or one of its dependencies could not be resolved` error

depend on plugin version 2.12-1.1.1640084764.9f463a9, and get `The following plugins are not marked as thread-safe` warning

**Expected behavior**
be able to use scala 2.12 and depend on a version that doesn't display the thread-safety warning

**Comment by SimonJPegg** [comment]
Hey @josephlbarnett 

there's an issue with building the 2.12 version of this plugin that I don't have the free time to dig into I'm afraid. I've dropped the 2.12 version from the builds.  If you want to look into it and get something working I'm happy to merge an MR.

Is there a reason you need 2.12 though?   AFIAK, maven just runs the code as a jar so the scala version it was compiled with makes no difference (happy to be told I'm wrong though).

**Comment by josephlbarnett** [comment]
thx for response @SimonJPegg.  I wasn't at all sure if it mattered or not but our scala codebase is 2.12 so went with that.  can play with 2.13 and see if it works, will report back if we find anything.

**Comment by josephlbarnett** [comment]
it does at least initially appear like using the 2.13 plugin on a 2.12 codebase works ok; not sure if there are corner cases where it won't

**Comment by SimonJPegg** [comment]
No worries.  I'll close this for now then.
