### ISSUE TITLE
Support new Scalafmt versions (1.6.0 and 2.0.0-RC5)

### ISSUE THREAD

**Issue by evis** [SimonJPegg/mvn_scalafmt#34]
Now the most recent supported version of Scalafmt is 1.5.1, though there are already 1.6.0 and 2.0.0-RC5 now.

**Comment by SimonJPegg** [comment]
Had a brief look on [Maven central](https://mvnrepository.com/artifact/com.geirsson/scalafmt-core) there, looks like the latest versions are 1.6.0-RC4 and 2.0.0-RC1.  I've pushed builds with those, but TBH, I don't plan on supporting release candidates.
