### ISSUE TITLE
Support scalafmt 2.0.0

### ISSUE THREAD

**Issue by codingismy11to7** [SimonJPegg/mvn_scalafmt#38]
I see #34 so I'm hesitant to open this, but...

I was going to submit a PR that built against all the current versions and also scalafmt 2.0.0...but the `groupId` for 2.0 changed to `org.scalameta`, so the build doesn't work. For now I just changed to only build against 2.0.0 and deployed it to our internal maven repo for our builds, but wanted to get a discussion going about an official release.

**Comment by SimonJPegg** [comment]
This should be addressed in [1.0.0-RC1](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/v1.0.0-RC1), [1.0.0-RC2](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/v1.0.0-RC2) and above.  I've re-written the plugin to use the new `scalafmt-dynamic` api, so the version of scalafmt used will be the one specified in your scalafmt.conf file.  The updated readme for the plugin is [here](https://github.com/SimonJPegg/mvn_scalafmt/blob/4a048082448e207665c6b0e636b019729fefa198/README.md).  This won't be merged to master (and a 1.0.0 release) until `scalafmt-dynamic` comes out of RC though.  

I can publish a updated `0.10_2.0.0-RCX` build if you need it though.

**Comment by SimonJPegg** [comment]
This should now now be resolved in versions 1.0.1 and above by specifying the version of scalafmt you wish to use in your config file.
