### ISSUE TITLE
respectVersion ignores incorrect versions

### ISSUE THREAD

**Issue by jozic** [SimonJPegg/mvn_scalafmt#42]
When `respectVersion` is set to `true`, I expect it to fail if version specified in the config file is incorrect. At the moment, plugin logs an error, but finishes the build with success, which may escape devs attention if the check is on CI only

**Comment by SimonJPegg** [comment]
Nothing I can do there I'm afraid.  `respectVersion` and the config are passed to the Scalafmt library itself [here](https://github.com/SimonJPegg/mvn_scalafmt/blob/master/src/main/scala/org/antipathy/mvn_scalafmt/ScalaFormatter.scala). As the variable is only used within the lib itself, it might be worth raising a bug against [scalafmt-dynamic](https://github.com/scalameta/scalafmt/tree/master/scalafmt-dynamic).
