### ISSUE TITLE
issue with parsing path to the config file in 1.0.1

### ISSUE THREAD

**Issue by cookienaut** [SimonJPegg/mvn_scalafmt#47]
hello! I've got strange issue with parsing path to the config file while upgrading to the version `1.0.1` from `0.12_1.5.1`.
Here is how my config location looks like
`<configLocation>${project.basedir}/../.scalafmt.conf</configLocation>`
in version `0.12_1.5.1` everything is working fine and scalafmt find config and in version `1.0.1` in fails with `Config path is invalid: /here/is/path/to/project_dir/../.scalafmt.conf`

**Comment by SimonJPegg** [comment]
Thanks for reporting.  I'm not able to reproduce this.  Can you post your pom file?

**Comment by SimonJPegg** [comment]
Closing this as there's been no reply.
