### ISSUE TITLE
Equivalent of --mode diff now that parameters have been removed?

### ISSUE THREAD

**Issue by koeninger** [SimonJPegg/mvn_scalafmt#48]
662b07bf7974f4f2427bfed6c9a59424ee98973f removed "parameters" as a configuration element.

I was using parameters to pass --mode diff, what is the equivalent now if I only want to format files that are modified compared to master?

For context, see e.g. https://github.com/apache/spark/pull/26655/files

**Comment by SimonJPegg** [comment]
There isn't an equivalent at the minute I'm afraid.  We're using Scalafmt-dynamic to pull down the requested version and are limited to the features supported by the [Scalafmt](https://github.com/scalameta/scalafmt/blob/master/scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/Scalafmt.java)  interface.  I'd have to re-implement this feature within the plugin.

**Comment by SimonJPegg** [comment]
Can you try [v1.0.3](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/v1.0.3) and let me know if this works for you.

**Comment by koeninger** [comment]
Testing it out now, thanks for the update

**Comment by SimonJPegg** [comment]
Judging by the comments on [SPARK-30570](https://github.com/apache/spark/pull/27279), I'm assuming this is now resolved.  Closing this issue.
