### ISSUE TITLE
Line ending based on OS rather than actual file format

### ISSUE THREAD

**Issue by joaquin-silva-truata** [SimonJPegg/mvn_scalafmt#52]
I work in a project that we maintain in both windows and mac computers. Our convention is using unix like EOL character ('\n') even in windows machines. Git allows you to do a auto EOL conversion but unfortunately our IDE takes that as a change in the file. On the other hand, we prefer not having any magic behind messing with the EOL. 

The thing is that, mvn_scalafmt uses `System.lineSeparator()` as a line separator in class `org.antipathy.mvn_scalafmt.format.SourceFileFormatter`. This causes that all files are rewritten always as `unformattedSource` never matches with formatted file output.

As a workaround I tried to use input JVM parameter `-Dline.separator=\n` but then weird things happen then: output from maven execution is unreadable, and the feature "onlyChangedFiles" is not able to parse correctly the changed files.

I am working on a solution to read files based on line endings of the file, rather than the OS expected EOL sequence. Basically it is a change in 
org.antipathy.mvn_scalafmt.format.SourceFileFormatter when retrieving `var unformattedSource`

**Comment by SimonJPegg** [comment]
Thanks for the PR. closing this issue
