### ISSUE TITLE
Unit tests not passing on Windows

### ISSUE THREAD

**Issue by joaquin-silva-truata** [SimonJPegg/mvn_scalafmt#53]
When you execute ScalaTests in Windows you will get 5 failed tests.

4 of them are due to unclosed files readers that cause errors when deleting configuration file. 
```
java.nio.file.FileSystemException: C:\Users\%Username%\AppData\Local\Temp\.scalafmt.conf: The process cannot access the file because it is being used by another process.
```
The 5th one is caused by the windows vs unix path format. In class `org.antipathy.mvn_scalafmt.builder.ChangedFilesBuilderSpec` paths are expected as starting by "/" while in windows paths start with "c:/"

See attached file with the test results:
[TestSuite.txt](https://github.com/SimonJPegg/mvn_scalafmt/files/4275058/TestSuite.txt)

**Comment by SimonJPegg** [comment]
Thanks for the PR. going to mark this issue as closed.
