### ISSUE TITLE
UTF-8 characters broken in Windows 

### ISSUE THREAD

**Issue by joaquin-silva-truata** [SimonJPegg/mvn_scalafmt#54]
**Prerequesites**
- Source file encoded in UTF-8 enclosing a UTF-8 character (like  "©" )
- Java 1.8.0_241 x64 bits
- Windows 10 OS (default encoding is "windows-1252")

**Bug description**
When I run mvn_scalafmt extension in windows with the conditions listed before, I would get the characters "Â©" written  instead of just "©"

**Cause**
As far as I could see the files are always written as "UTF-8" but they are read using the default environment character encoding. 

If you combine this issue with the issue in https://github.com/SimonJPegg/mvn_scalafmt/issues/52 , that causes the files are rewritten every time a maven validation phase is executed, you end up having files which size grows exponentially.

**Workaround**
This issue can be fixed in Windows by ensuring that the flag `-D"file.encoding=UTF-8"` is added to the maven execution. Note that I had to add the quotes around the parameter definition. Otherwise it wouldn't work in Windows. See comment from cabaji99 to [this response in StackOverflow](https://stackoverflow.com/a/362006) for details.

**Additional comments**
My concern here is why we are always writing files as UTF-8 but not reading them as such. I think we should ensure both encodings are the same. Ideally I would detect the encoding of the source file, and I would write it back using the same format. Another possibility would be to take System.getProperty("file.encoding") as the file encoding for both file reading and writing.

**Comment by SimonJPegg** [comment]
Thanks, code to resolve this has been added to master.  Will push with next release

**Comment by SimonJPegg** [comment]
Hi @joaquin-silva-truata can you check if this is still an issue with the new release?

**Comment by joaquin-silva-truata** [comment]
Hi @SimonJPegg Issue is no longer happening. Thank you very much!!

**Comment by SimonJPegg** [comment]
Thanks, going to mark this as resolved
