### ISSUE TITLE
Failed to execute when no parameters are added.

### ISSUE THREAD

**Issue by rhpvorderman** [SimonJPegg/mvn_scalafmt#8]
I get the following error when I leave out the parameters section:
Failed to execute goal org.antipathy:mvn-scalafmt:0.6.8:format (default) on project ... : Error formatting Scala files: NullPointerException -> [Help 1]

When I add 
```xml
<parameters>--non-interactive</parameters>
```
everything works. --debug also works.

**Comment by SimonJPegg** [comment]
This should be resolved in 0.3_0.6.X
