### ISSUE TITLE
Maven compile error due to version

### ISSUE THREAD

**Issue by mangrrua** [SimonJPegg/mvn_scalafmt#87]
This plugin only accepts maven 3.6.0? I'm getting error; 

`The plugin org.antipathy:mvn-scalafmt_2.12:1.0.1595019692.1dd1d1f requires Maven version 3.6.0`

I'm using this plugin for the first time, and i do not good in maven. I do not know how can i solve this problem

**Comment by bmk93** [comment]
Facing same issue. Local maven version is 3.3.9. Is it mandatory to match 3.6.0 version ?

**Comment by SimonJPegg** [comment]
@mangrrua @bmk93, the plugin depends on part of the api defined in maven 3.6.0 and checks to ensure that the running version is at least 3.6.  It will throw the message you're receiving if it finds an earlier version.

**Comment by bmk93** [comment]
Thanks @SimonJPegg. Build is failing on CI server which happens to have 3.3.9 version of maven. Is there a workaround to use this plugin with lower version of maven ? 
I have seen that plugin versions <=0.7 seem to have maven dependency matching 3.3.9. Is it the only way ?

**Comment by SimonJPegg** [comment]
@bmk93 I believe the only options open to you are:

* use an earlier version of the plugin.
* upgrade to a newer maven version on the CI server.
* Two [build profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) (CI+no plugin/ local + plugin).  

The last one would let you upgrade your local maven version and use a recent release of the plugin, but you'd have to ensure that everyone commiting runs the plugin first (which kind of defeats the purpose).
