### ISSUE TITLE
mvn-scalafmt and scalafmt version are the same.

### ISSUE THREAD

**Issue by rhpvorderman** [SimonJPegg/mvn_scalafmt#9]
mvn-scalafmt and scalafmt now track the same version. How does it work when:
- a feature is added to mvn-scalafmt? Will mvn-scalafmt-0.6.8 be updated as well, even though it is the same version? Or do I need to step up to a newer version of scalafmt to get a newer version of mvn-scalafmt?
- I want to use the newest version of mvn-scalafmt with an older version of scalafmt?

It might be cleaner to separate out the scalafmt version and the mvn-scalafmt version so these things are never an issue.

**Comment by SimonJPegg** [comment]
Version now contains both the plugin version and the scalafmt version, you can update your pom to include 0.3_0.6.X
