### ISSUE TITLE
Fail build when code is not formatted

### ISSUE THREAD

**Issue by cosminci** [SimonJPegg/mvn_scalafmt#97]
There doesn't seem to be any automated way to enforce the formatting standard, and this would be really helpful to avoid having to look through CI logs to see that the code is correctly formatted for every PR.

The CI system reformats the code during build, but it can't commit the changes to SCM.

Adding a flag that fails the build when any file is not formatted according to the scalafmt configuration would be a nice feature.

**Comment by SimonJPegg** [comment]
`<validateOnly>true</validateOnly>` the plugin configuration should do that.
